version: '3'
services:
  nginx: 
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sujay
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    # command: ["redis", "--bind", "redis", "--port", "6379"]

volumes:
  mongo-db: