version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sujay
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis:latest 
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'

volumes:
  mongo-db: